### ISSUE TITLE
Wrong enum for the depth buffer comparison function

### ISSUE THREAD

**Issue by eighteight** [sosolimited/Entity-Component-Samples#31]
My console is flooded with the following lines in the StarClusters sample, compiled out of the box:

```
error  | void cinder::gl::Context::pushDepthFunc(GLenum)[1475] Wrong enum for the depth buffer comparison function

```

**Comment by sansumbrella** [comment]
I'm guessing this is due to a recent change in Cinder's `gl::Scoped*` scoped objects.

Try removing the second parameter to the gl::ScopedDepth objects. It used to be required for setting read/write separately.

**Comment by sansumbrella** [comment]
[This change to Cinder](https://github.com/cinder/Cinder/commit/9c402bbd2fe830a2ead635ac3ac76d05fa760607)

**Comment by sansumbrella** [comment]
Thanks for catching that!

**Comment by eighteight** [comment]
Confirming that the error is gone. I am looking into using this approach to create something with a lot of audioreactive items, similar to ryoji ikeda. Do you think I might hit some bottlenecks when I create hundreds of entities?

**Comment by sansumbrella** [comment]
Hundreds of entities will be no problem. In the past, I built a scene with tens of thousands of animated sprites using entities and components and performance was great (~12ms per frame on my 2011 mbp).

The main thing to look out for with lots of entities is how you do your rendering. Fortunately, using an ECS makes it straightforward to grab things for batching/instancing. Also, it makes it easy to measure the performance of different parts of your code.

e.g.
```
auto bar = ComponentHandle<Bar>();
auto position = ComponentHandle<Position>();
for (auto e: entities.entities_with_components(bar, position)){
  instance_data.push({bar->rectangle, position->position});
}
// now buffer your instance data and issue a single draw call...
```

The samples don't go down the rendering performance rabbit-hole, so their bottleneck is really in the multiple calls to gl::drawSolidCircle.

**Comment by eighteight** [comment]
Nice, thanks for the suggestion to use instancing.
